name = "ISML"
grammar = "isml"
path_suffixes = ["isml"]
block_comment = ["<iscomment>", "</iscomment>"]
autoclose_before = ";:.,=}])>\"' "
tab_size = 4

brackets = [
  { start = "<", end = ">", close = false, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]
